### ISSUE TITLE
ArgumentNullException thrown while calling CreateMap with object that has a collection member

### ISSUE THREAD

**Issue by clifflau1120-accenture** [AutoMapper/AutoMapper.Data#44]
```
public class MemberDto
{
    public IList<CardDto> Cards { get; set; }
}

public class CardDto
{
    public string CardNumber { get; set; }
    public string Amount { get; set; }
}

public sealed class MemberProfile : Profile
{
    AddMemberConfiguration()
        .AddMember<DataRecordMemberConfiguration>();
    CreateMap<IDataReader, MemberDto>()
        .ForMember(dest => dest.Cards, opt => opt.Ignore());
}

var config = new MapperConfiguration(cfg =>
{
    cfg.AddMaps(GetType().Assembly); // This throws "Value cannot be null. Parameter name: con"
});
```

Tried to solve it for hours... Anyone having the same issue?

**Comment by ColonelDuddits** [comment]
The exception is thrown because `IList` has no default constructor. I've been considering setting properties like that to their default value. I've also considered throwing a more detailed exception that AutoMapper can handle or ignore. Does anyone have any arguments for or against either of these approaches?

**Comment by lbargaoanu** [comment]
In AM when we cannot map smth, we throw. Of course a useful error message is always good. But, unless I'm mistaken, you cannot really ignore unmapped members. So it would be kind of strict to disallow cases like this. Not necessarily unreasonable (it might simply be an error), but I think people would appreciate a default instead.
